title: trappsec
description: deception as a developer tool
url: "https://trappsec.dev"

heading_anchors: true

aux_links:
  "GitHub": "https://github.com/trappsec-dev/trappsec"

exclude: [Gemfile, Gemfile.lock]

footer_content: "Copyright &copy; 2026 trappsec"
